// Quality problem bank for Code Royale practice.
// Every problem uses the LeetCode-style signature model (see src/lib/harness.ts)
// with plain, whitespace-delimited inputs and byte-exact outputs. Each entry
// carries a canonical Python solution used only to verify the bank before seed.
export const QUALITY_BANK = [
  // ─────────────────────────── EASY ───────────────────────────
  {
    slug: "sum-two-numbers",
    title: "Sum of Two Numbers",
    description: "Return the sum of the two given integers.\n\nInput: two space-separated integers\nOutput: an integer",
    difficulty: "easy",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "a", type: "int" }, { name: "b", type: "int" }], returns: "int" },
    testcases: [
      { input: "3 4", output: "7" },
      { input: "-5 9", output: "4" },
      { input: "0 0", output: "0" },
    ],
    python: "def solve(a: int, b: int) -> int:\n    return a + b",
  },
  {
    slug: "largest-of-three",
    title: "Largest of Three",
    description: "Return the largest of the three given integers.\n\nInput: three space-separated integers\nOutput: an integer",
    difficulty: "easy",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "a", type: "int" }, { name: "b", type: "int" }, { name: "c", type: "int" }], returns: "int" },
    testcases: [
      { input: "3 9 2", output: "9" },
      { input: "-1 -5 -2", output: "-1" },
      { input: "7 7 3", output: "7" },
    ],
    python: "def solve(a: int, b: int, c: int) -> int:\n    return max(a, b, c)",
  },
  {
    slug: "even-or-odd",
    title: "Even or Odd",
    description: 'Return "Even" if the given integer is even, otherwise "Odd".\n\nInput: an integer\nOutput: Even or Odd',
    difficulty: "easy",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "n", type: "int" }], returns: "str" },
    testcases: [
      { input: "4", output: "Even" },
      { input: "7", output: "Odd" },
      { input: "0", output: "Even" },
    ],
    python: 'def solve(n: int) -> str:\n    return "Even" if n % 2 == 0 else "Odd"',
  },
  {
    slug: "reverse-string",
    title: "Reverse a String",
    description: "Return the reverse of the given string.\n\nInput: a single string with no spaces\nOutput: the reversed string",
    difficulty: "easy",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "s", type: "str" }], returns: "str" },
    testcases: [
      { input: "hello", output: "olleh" },
      { input: "a", output: "a" },
      { input: "racecar", output: "racecar" },
    ],
    python: "def solve(s: str) -> str:\n    return s[::-1]",
  },
  {
    slug: "factorial",
    title: "Factorial",
    description: "Return the factorial of the given non-negative integer.\n\nInput: a non-negative integer n\nOutput: n!",
    difficulty: "easy",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "n", type: "int" }], returns: "int" },
    testcases: [
      { input: "5", output: "120" },
      { input: "0", output: "1" },
      { input: "1", output: "1" },
    ],
    python: "def solve(n: int) -> int:\n    r = 1\n    for i in range(2, n + 1): r *= i\n    return r",
  },
  {
    slug: "array-sum",
    title: "Array Sum",
    description: "Return the sum of all integers in the input array.\n\nInput: a line of space-separated integers\nOutput: an integer",
    difficulty: "easy",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "nums", type: "list[int]" }], returns: "int" },
    testcases: [
      { input: "1 2 3 4", output: "10" },
      { input: "-2 5 -1", output: "2" },
      { input: "0 0 0", output: "0" },
    ],
    python: "def solve(nums: list[int]) -> int:\n    return sum(nums)",
  },
  {
    slug: "max-of-array",
    title: "Maximum Element",
    description: "Return the maximum value in the input array. The array is non-empty.\n\nInput: a line of space-separated integers\nOutput: an integer",
    difficulty: "easy",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "nums", type: "list[int]" }], returns: "int" },
    testcases: [
      { input: "3 7 2 9", output: "9" },
      { input: "-5 -2 -9", output: "-2" },
      { input: "5", output: "5" },
    ],
    python: "def solve(nums: list[int]) -> int:\n    return max(nums)",
  },
  {
    slug: "is-sorted",
    title: "Is Array Sorted",
    description: 'Return true if the array is sorted in non-decreasing order, else false.\n\nInput: a line of space-separated integers\nOutput: true or false',
    difficulty: "easy",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "nums", type: "list[int]" }], returns: "bool" },
    testcases: [
      { input: "1 2 2 5", output: "true" },
      { input: "3 1 2", output: "false" },
      { input: "1 2 3", output: "true" },
    ],
    python: "def solve(nums: list[int]) -> bool:\n    return all(nums[i] <= nums[i + 1] for i in range(len(nums) - 1))",
  },
  {
    slug: "gcd",
    title: "Greatest Common Divisor",
    description: "Return the greatest common divisor of the two given integers.\n\nInput: two space-separated integers\nOutput: an integer",
    difficulty: "easy",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "a", type: "int" }, { name: "b", type: "int" }], returns: "int" },
    testcases: [
      { input: "12 18", output: "6" },
      { input: "17 13", output: "1" },
      { input: "0 5", output: "5" },
    ],
    python: "def solve(a: int, b: int) -> int:\n    while b: a, b = b, a % b\n    return abs(a)",
  },
  {
    slug: "count-target",
    title: "Count Occurrences",
    description: "Count how many times target appears in the array.\n\nInput: the array length, then the array, then the target\nOutput: an integer",
    difficulty: "easy",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "nums", type: "list[int]" }, { name: "target", type: "int" }], returns: "int" },
    testcases: [
      { input: "5 1 2 2 2 3 2", output: "3" },
      { input: "2 4 5 6", output: "0" },
      { input: "4 9 9 9 9 9", output: "4" },
    ],
    python: "def solve(nums: list[int], target: int) -> int:\n    return nums.count(target)",
  },

  // ─────────────────────────── MEDIUM ───────────────────────────
  {
    slug: "two-sum",
    title: "Two Sum",
    description: "Return the indices of the two numbers that add up to target. Exactly one solution exists.\n\nInput: the array length, then the array, then the target\nOutput: the two indices, space-separated",
    difficulty: "medium",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "nums", type: "list[int]" }, { name: "target", type: "int" }], returns: "list[int]" },
    testcases: [
      { input: "4 2 7 11 15 9", output: "0 1" },
      { input: "3 3 2 4 6", output: "1 2" },
      { input: "2 3 3 6", output: "0 1" },
    ],
    python: "def solve(nums: list[int], target: int) -> list[int]:\n    seen = {}\n    for i, v in enumerate(nums):\n        if target - v in seen:\n            return [seen[target - v], i]\n        seen[v] = i\n    return []",
  },
  {
    slug: "rotate-array",
    title: "Rotate Array",
    description: "Rotate the array to the right by k steps.\n\nInput: the array length, then the array, then k\nOutput: the rotated array, space-separated",
    difficulty: "medium",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "nums", type: "list[int]" }, { name: "k", type: "int" }], returns: "list[int]" },
    testcases: [
      { input: "4 1 2 3 4 1", output: "4 1 2 3" },
      { input: "4 1 2 3 4 7", output: "2 3 4 1" },
      { input: "3 1 2 3 0", output: "1 2 3" },
    ],
    python: "def solve(nums: list[int], k: int) -> list[int]:\n    k %= len(nums)\n    return nums[-k:] + nums[:-k] if k else nums",
  },
  {
    slug: "remove-duplicates",
    title: "Remove Duplicates",
    description: "Return the array with duplicate values removed, keeping the first occurrence of each value in order.\n\nInput: a line of space-separated integers\nOutput: the deduplicated array, space-separated",
    difficulty: "medium",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "nums", type: "list[int]" }], returns: "list[int]" },
    testcases: [
      { input: "1 2 2 3", output: "1 2 3" },
      { input: "3 3 3 3", output: "3" },
      { input: "2 3 3 2", output: "2 3" },
    ],
    python: "def solve(nums: list[int]) -> list[int]:\n    seen = set()\n    out = []\n    for v in nums:\n        if v not in seen:\n            seen.add(v)\n            out.append(v)\n    return out",
  },
  {
    slug: "valid-parentheses",
    title: "Valid Parentheses",
    description: 'Return true if the parentheses string is valid (properly closed and nested), else false.\n\nInput: a string made of ()[]{} with no spaces\nOutput: true or false',
    difficulty: "medium",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "s", type: "str" }], returns: "bool" },
    testcases: [
      { input: "()[]{}", output: "true" },
      { input: "(]", output: "false" },
      { input: "({[)]}", output: "false" },
    ],
    python: "def solve(s: str) -> bool:\n    stack = []\n    pairs = {')': '(', ']': '[', '}': '{'}\n    for c in s:\n        if c in pairs:\n            if not stack or stack.pop() != pairs[c]:\n                return False\n        else:\n            stack.append(c)\n    return not stack",
  },
  {
    slug: "binary-search",
    title: "Binary Search",
    description: "Return the index of target in the sorted array, or -1 if it is absent.\n\nInput: the array length, then the sorted array, then the target\nOutput: an index or -1",
    difficulty: "medium",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "nums", type: "list[int]" }, { name: "target", type: "int" }], returns: "int" },
    testcases: [
      { input: "4 1 3 5 7 5", output: "2" },
      { input: "4 1 3 5 7 2", output: "-1" },
      { input: "1 10 10", output: "0" },
    ],
    python: "def solve(nums: list[int], target: int) -> int:\n    lo, hi = 0, len(nums) - 1\n    while lo <= hi:\n        m = (lo + hi) // 2\n        if nums[m] == target: return m\n        if nums[m] < target: lo = m + 1\n        else: hi = m - 1\n    return -1",
  },
  {
    slug: "first-unique-character",
    title: "First Unique Character",
    description: "Return the index of the first non-repeating character, or -1 if every character repeats.\n\nInput: a string with no spaces\nOutput: an index or -1",
    difficulty: "medium",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "s", type: "str" }], returns: "int" },
    testcases: [
      { input: "swiss", output: "1" },
      { input: "aabbcc", output: "-1" },
      { input: "loveleetcode", output: "2" },
    ],
    python: "def solve(s: str) -> int:\n    from collections import Counter\n    c = Counter(s)\n    for i, ch in enumerate(s):\n        if c[ch] == 1:\n            return i\n    return -1",
  },
  {
    slug: "move-zeroes",
    title: "Move Zeroes",
    description: "Move all zeroes to the end, preserving the relative order of the non-zero elements.\n\nInput: a line of space-separated integers\nOutput: the rearranged array, space-separated",
    difficulty: "medium",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "nums", type: "list[int]" }], returns: "list[int]" },
    testcases: [
      { input: "0 1 0 3 12", output: "1 3 12 0 0" },
      { input: "0 0 1", output: "1 0 0" },
      { input: "4 5", output: "4 5" },
    ],
    python: "def solve(nums: list[int]) -> list[int]:\n    nz = [v for v in nums if v != 0]\n    return nz + [0] * (len(nums) - len(nz))",
  },
  {
    slug: "max-profit",
    title: "Best Time to Buy and Sell",
    description: "Return the maximum profit from one buy and one sell across the price array (0 if none is profitable).\n\nInput: a line of space-separated prices\nOutput: an integer",
    difficulty: "medium",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "prices", type: "list[int]" }], returns: "int" },
    testcases: [
      { input: "7 1 5 3 6 4", output: "5" },
      { input: "7 6 4 3 1", output: "0" },
      { input: "2 4 1", output: "2" },
    ],
    python: "def solve(prices: list[int]) -> int:\n    best = 0\n    low = prices[0] if prices else 0\n    for p in prices:\n        best = max(best, p - low)\n        low = min(low, p)\n    return best",
  },

  // ─────────────────────────── HARD ───────────────────────────
  {
    slug: "maximum-subarray",
    title: "Maximum Subarray",
    description: "Return the sum of the contiguous subarray with the largest sum.\n\nInput: a line of space-separated integers\nOutput: an integer",
    difficulty: "hard",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "nums", type: "list[int]" }], returns: "int" },
    testcases: [
      { input: "-2 1 -3 4 -1 2 1 -5 4", output: "6" },
      { input: "-2 -1", output: "-1" },
      { input: "-1 2 3 4", output: "9" },
    ],
    python: "def solve(nums: list[int]) -> int:\n    best = cur = nums[0]\n    for v in nums[1:]:\n        cur = max(v, cur + v)\n        best = max(best, cur)\n    return best",
  },
  {
    slug: "product-except-self",
    title: "Product of Array Except Self",
    description: "Return an array where each element is the product of all other elements. Do not use division.\n\nInput: a line of space-separated integers\nOutput: the products, space-separated",
    difficulty: "hard",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "nums", type: "list[int]" }], returns: "list[int]" },
    testcases: [
      { input: "1 2 3 4", output: "24 12 8 6" },
      { input: "-1 0 1", output: "0 -1 0" },
      { input: "2 3", output: "3 2" },
    ],
    python: "def solve(nums: list[int]) -> list[int]:\n    n = len(nums)\n    out = [1] * n\n    left = 1\n    for i in range(n):\n        out[i] = left\n        left *= nums[i]\n    right = 1\n    for i in range(n - 1, -1, -1):\n        out[i] *= right\n        right *= nums[i]\n    return out",
  },
  {
    slug: "sort-colors",
    title: "Sort Colors",
    description: "Sort the array where every value is 0, 1, or 2, in-place, in linear time and constant space.\n\nInput: a line of space-separated integers (0, 1, or 2)\nOutput: the sorted array, space-separated",
    difficulty: "hard",
    languages: ["javascript", "python", "cpp", "java", "c"],
    signature: { params: [{ name: "colors", type: "list[int]" }], returns: "list[int]" },
    testcases: [
      { input: "2 0 2 1 1 0", output: "0 0 1 1 2 2" },
      { input: "2 0 1", output: "0 1 2" },
      { input: "1 1 1", output: "1 1 1" },
    ],
    python: "def solve(colors: list[int]) -> list[int]:\n    a = sorted(colors)\n    return a",
  },
];